apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        app: webserver
    spec:
      containers:
        - name: webserver
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: host-vol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: host-vol
          hostPath:
            path: /home/docker/vol
